### ISSUE TITLE
Adding 'removeGroup' and 'getGroup' methods.

### ISSUE THREAD

**Issue by kbirk** [unchartedsoftware/stories-facets#11]
Hey,

I have use cases for the following functionality:

- Removing groups from a `Facets` object:
	- Adding a `removeGroup(key)` method.	
- Retrieving a group from the `Facets` object:
	- Exposing the current `_getGroup(key)` method as `getGroup(key)`

All above methods seem like very low hanging fruit and I am happy to implement them and open a PR if there are no objections.

**Comment by darionco** [comment]
That would be great, thanks.
